import React from "react";
import { ShipmentResponse, ShipmentStatus } from "../types";
import {
  X,
  Truck,
  CheckCircle,
  Clock,
  Package,
  MapPin,
  Calendar,
  AlertCircle,
} from "lucide-react";

interface ShipmentTrackingModalProps {
  isOpen: boolean;
  onClose: () => void;
  shipment: ShipmentResponse | null;
  isLoading: boolean;
  orderId: number | null;
}

const STEPS: { status: ShipmentStatus; label: string; desc: string }[] = [
  { status: "CREATED", label: "Manifest Created", desc: "Shipping label generated by seller" },
  { status: "PICKED_UP", label: "Picked Up", desc: "Courier received parcel at fulfillment center" },
  { status: "IN_TRANSIT", label: "In Transit", desc: "Package moving through logistics hub network" },
  { status: "OUT_FOR_DELIVERY", label: "Out for Delivery", desc: "With local delivery partner on vehicle" },
  { status: "DELIVERED", label: "Delivered", desc: "Package successfully handed over to recipient" },
];

export const ShipmentTrackingModal: React.FC<ShipmentTrackingModalProps> = ({
  isOpen,
  onClose,
  shipment,
  isLoading,
  orderId,
}) => {
  if (!isOpen) return null;

  const currentStatusIndex = shipment
    ? STEPS.findIndex((s) => s.status === shipment.status)
    : -1;

  const isReturned = shipment?.status === "RETURNED";

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto flex items-center justify-center p-4">
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-slate-900/50 backdrop-blur-xs transition-opacity"
        onClick={onClose}
      />

      {/* Modal Dialog */}
      <div className="relative bg-white rounded-2xl max-w-lg w-full shadow-2xl border border-slate-100 overflow-hidden z-10 flex flex-col">
        {/* Header */}
        <div className="p-5 border-b border-slate-100 flex items-center justify-between bg-slate-50/70">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center">
              <Truck className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900">
                Live Shipment Tracking
              </h3>
              <p className="text-xs text-slate-500">Order #{orderId}</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-700 hover:bg-slate-200 transition cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-5 sm:p-6 space-y-6">
          {isLoading ? (
            <div className="py-12 flex flex-col items-center justify-center space-y-3">
              <div className="w-8 h-8 border-3 border-blue-600 border-t-transparent rounded-full animate-spin" />
              <p className="text-xs font-medium text-slate-500">
                Retrieving live courier coordinates...
              </p>
            </div>
          ) : !shipment ? (
            <div className="text-center py-10 space-y-2">
              <Clock className="w-10 h-10 text-amber-500 mx-auto" />
              <h4 className="font-bold text-slate-800 text-sm">
                Shipment Not Yet Dispatched
              </h4>
              <p className="text-xs text-slate-500 max-w-xs mx-auto">
                The warehouse team is currently packing your order. Live tracking will activate once picked up by the courier.
              </p>
            </div>
          ) : (
            <>
              {/* Quick Info Grid */}
              <div className="grid grid-cols-2 gap-3 bg-slate-50 rounded-xl p-3.5 border border-slate-200 text-xs">
                <div>
                  <span className="text-slate-400 block font-medium">Tracking #</span>
                  <span className="font-mono font-bold text-slate-800 break-all">
                    {shipment.trackingNumber}
                  </span>
                </div>
                <div>
                  <span className="text-slate-400 block font-medium">Courier Partner</span>
                  <span className="font-bold text-slate-800 flex items-center gap-1">
                    <Package className="w-3.5 h-3.5 text-blue-600" />
                    {shipment.courierName}
                  </span>
                </div>
                <div>
                  <span className="text-slate-400 block font-medium">Current Location</span>
                  <span className="font-bold text-slate-800 flex items-center gap-1 truncate">
                    <MapPin className="w-3.5 h-3.5 text-rose-500 shrink-0" />
                    {shipment.currentLocation}
                  </span>
                </div>
                <div>
                  <span className="text-slate-400 block font-medium">Estimated Delivery</span>
                  <span className="font-bold text-slate-800 flex items-center gap-1">
                    <Calendar className="w-3.5 h-3.5 text-emerald-600" />
                    {shipment.estimatedDelivery || "Calculating..."}
                  </span>
                </div>
              </div>

              {isReturned && (
                <div className="p-3 bg-rose-50 border border-rose-200 rounded-xl flex items-center gap-2 text-xs text-rose-800">
                  <AlertCircle className="w-4 h-4 text-rose-600 shrink-0" />
                  <span>
                    This shipment was marked as <strong>RETURNED TO ORIGIN</strong> by the carrier.
                  </span>
                </div>
              )}

              {/* Step Progress Timeline */}
              <div className="space-y-4 pt-2">
                <h4 className="text-xs font-bold text-slate-700 uppercase tracking-wider">
                  Checkpoint Timeline
                </h4>
                <div className="relative pl-6 space-y-6 before:absolute before:left-2.5 before:top-2 before:bottom-2 before:w-0.5 before:bg-slate-200">
                  {STEPS.map((step, idx) => {
                    const isCompleted = currentStatusIndex >= idx;
                    const isCurrent = currentStatusIndex === idx;

                    return (
                      <div key={step.status} className="relative flex items-start group">
                        {/* Dot indicator */}
                        <div
                          className={`absolute -left-6 top-0.5 w-5 h-5 rounded-full flex items-center justify-center ring-4 ring-white transition ${
                            isCompleted
                              ? "bg-blue-600 text-white"
                              : "bg-slate-200 text-slate-400"
                          } ${isCurrent ? "ring-blue-100 animate-pulse" : ""}`}
                        >
                          {isCompleted ? (
                            <CheckCircle className="w-3 h-3" />
                          ) : (
                            <div className="w-1.5 h-1.5 bg-slate-400 rounded-full" />
                          )}
                        </div>

                        {/* Text */}
                        <div className="ml-2">
                          <div className="flex items-center gap-2">
                            <span
                              className={`text-xs font-bold ${
                                isCompleted ? "text-slate-900" : "text-slate-400"
                              }`}
                            >
                              {step.label}
                            </span>
                            {isCurrent && (
                              <span className="px-1.5 py-0.5 text-[10px] font-bold bg-blue-100 text-blue-800 rounded">
                                ACTIVE
                              </span>
                            )}
                          </div>
                          <p className="text-[11px] text-slate-500 mt-0.5 leading-snug">
                            {step.desc}
                          </p>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>

              {/* Timestamp */}
              <div className="text-[11px] text-slate-400 text-right pt-2 border-t border-slate-100">
                Last checkpoint update: {new Date(shipment.updatedAt).toLocaleString()}
              </div>
            </>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 bg-slate-50 border-t border-slate-100 flex justify-end">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white text-xs font-semibold rounded-xl transition cursor-pointer"
          >
            Close Tracking
          </button>
        </div>
      </div>
    </div>
  );
};
